name: 构建TypeScript

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tsconfig.json'
      - 'package.json'
      - '.github/workflows/build.yml'
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write  # 需要写入权限才能提交

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        # 确保获取完整历史以便于推送
        fetch-depth: 0
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 构建TypeScript
      run: npm run build
      
    - name: 复制数据文件
      run: |
        mkdir -p dist
        if [ -f src/data.txt ]; then
          cp src/data.txt dist/
          echo "✅ 数据文件已复制到dist目录"
        else
          echo "⚠️ 数据文件不存在，跳过复制"
        fi
      
    - name: 提交编译后的文件
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -f dist/
        if git diff --staged --quiet; then
          echo "没有变更需要提交"
        else
          git commit -m "自动构建: 更新编译后的JavaScript文件"
          # 添加调试信息
          echo "开始推送更改..."
          git push
          echo "✅ 编译后的文件已提交"
        fi 